# Generated by Django 6.0 on 2025-12-24 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="voter_id",
            field=models.CharField(
                blank=True,
                help_text="External voter file ID",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="VoterRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registered_party", models.CharField(blank=True, max_length=50)),
                ("gender", models.CharField(blank=True, max_length=1)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("ethnicity", models.CharField(blank=True, max_length=100)),
                ("marital_status", models.CharField(blank=True, max_length=20)),
                ("spoken_language", models.CharField(blank=True, max_length=50)),
                ("military_status", models.CharField(blank=True, max_length=50)),
                ("changed_party", models.BooleanField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("apartment_type", models.CharField(blank=True, max_length=50)),
                ("street_number_parity", models.CharField(blank=True, max_length=10)),
                ("cell_phone_confidence", models.CharField(blank=True, max_length=10)),
                ("likelihood_general", models.CharField(blank=True, max_length=20)),
                ("likelihood_primary", models.CharField(blank=True, max_length=20)),
                ("likelihood_combined", models.CharField(blank=True, max_length=20)),
                ("voted_general_2024", models.BooleanField(blank=True, null=True)),
                ("voted_general_2022", models.BooleanField(blank=True, null=True)),
                ("voted_general_2020", models.BooleanField(blank=True, null=True)),
                ("voted_general_2018", models.BooleanField(blank=True, null=True)),
                ("voted_primary_2024", models.BooleanField(blank=True, null=True)),
                ("voted_primary_2022", models.BooleanField(blank=True, null=True)),
                ("voted_primary_2020", models.BooleanField(blank=True, null=True)),
                ("voted_primary_2018", models.BooleanField(blank=True, null=True)),
                ("household_party", models.CharField(blank=True, max_length=100)),
                (
                    "mailing_household_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("mailing_family_id", models.CharField(blank=True, max_length=50)),
                (
                    "mailing_household_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "mailing_household_party",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_record",
                        to="civicpulse.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "voter record",
                "verbose_name_plural": "voter records",
            },
        ),
    ]
