# Generated by Django 6.0 on 2025-12-24 05:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0002_person_voter_id_voterrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactEffort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "script",
                    models.TextField(
                        blank=True,
                        help_text="Script or talking points for callers/texters",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_efforts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("call", "Phone Call"), ("text", "Text Message")],
                        default="call",
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("no_answer", "No Answer"),
                            ("busy", "Busy Signal"),
                            ("left_voicemail", "Left Voicemail"),
                            ("wrong_number", "Wrong Number"),
                            ("spoke_with", "Spoke With Person"),
                            ("refused", "Refused/Do Not Contact"),
                            ("callback_requested", "Callback Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Conversation details or notes"
                    ),
                ),
                (
                    "phone_number_used",
                    models.CharField(
                        blank=True,
                        help_text="The phone number that was called/texted",
                        max_length=20,
                    ),
                ),
                (
                    "callback_time",
                    models.DateTimeField(
                        blank=True, help_text="Requested callback time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contacted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_attempts",
                        to="civicpulse.person",
                    ),
                ),
                (
                    "effort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="civicpulse.contacteffort",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["effort", "person"],
                        name="civicpulse__effort__f6c2be_idx",
                    ),
                    models.Index(
                        fields=["effort", "outcome"],
                        name="civicpulse__effort__e131c9_idx",
                    ),
                ],
            },
        ),
    ]
