# Generated by Django 6.0 on 2025-12-24 05:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0003_contacteffort_contactattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EffortAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "effort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="civicpulse.contacteffort",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caller currently working on this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effort_assignments",
                        to="civicpulse.person",
                    ),
                ),
            ],
            options={
                "ordering": ["assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["effort", "status"],
                        name="civicpulse__effort__4f095b_idx",
                    ),
                    models.Index(
                        fields=["locked_by", "locked_at"],
                        name="civicpulse__locked__567e53_idx",
                    ),
                ],
                "unique_together": {("effort", "person")},
            },
        ),
    ]
