# Generated by Django 6.0 on 2025-12-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0006_add_will_vote_outcome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"ordering": ["-election__year", "name"]},
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="candidate",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Candidate name (used if not linked to a Person record)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to an existing Person record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidacies",
                to="civicpulse.person",
            ),
        ),
    ]
