# Generated by Django 6.0 on 2025-12-24 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0007_candidate_optional_person_add_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactattempt",
            name="address_visited",
            field=models.ForeignKey(
                blank=True,
                help_text="The address visited for door knock attempts",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_attempts",
                to="civicpulse.address",
            ),
        ),
        migrations.AlterField(
            model_name="contactattempt",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("text", "Text Message"),
                    ("door_knock", "Door Knock"),
                ],
                default="call",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contactattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("no_answer", "No Answer"),
                    ("busy", "Busy Signal"),
                    ("left_voicemail", "Left Voicemail"),
                    ("wrong_number", "Wrong Number"),
                    ("spoke_with", "Spoke With Person"),
                    ("will_vote", "Will Vote for Candidate"),
                    ("refused", "Refused/Do Not Contact"),
                    ("callback_requested", "Callback Requested"),
                    ("not_home", "Not Home"),
                    ("left_door_hanger", "Left Door Hanger"),
                    ("spoke_at_door", "Spoke at Door"),
                    ("refused_door", "Refused to Answer Door"),
                    ("no_access", "No Access (Gated/Locked)"),
                ],
                max_length=20,
            ),
        ),
    ]
