# Generated by Django 6.0 on 2025-12-27 05:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0008_add_door_knock_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoterAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('mailing', 'Mailing')], default='home', max_length=10)),
                ('street_address', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='US state abbreviation', max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'voter addresses',
                'ordering': ['-is_primary', 'type'],
            },
        ),
        migrations.CreateModel(
            name='VoterEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('other', 'Other')], default='personal', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'type'],
            },
        ),
        migrations.CreateModel(
            name='VoterPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='mobile', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='effortassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contacteffort',
            name='uses_election_voters',
            field=models.BooleanField(default=False, help_text='If True, uses ElectionVoter records instead of Person records'),
        ),
        migrations.AlterField(
            model_name='contactattempt',
            name='address_visited',
            field=models.ForeignKey(blank=True, help_text='The address visited for door knock attempts (Person)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_attempts', to='civicpulse.address'),
        ),
        migrations.AlterField(
            model_name='contactattempt',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='civicpulse.person'),
        ),
        migrations.AlterField(
            model_name='effortassignment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effort_assignments', to='civicpulse.person'),
        ),
        migrations.CreateModel(
            name='ElectionVoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(help_text='External voter file ID (unique within this election)', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('registered_party', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('spoken_language', models.CharField(blank=True, max_length=50)),
                ('military_status', models.CharField(blank=True, max_length=50)),
                ('changed_party', models.BooleanField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('apartment_type', models.CharField(blank=True, max_length=50)),
                ('street_number_parity', models.CharField(blank=True, max_length=10)),
                ('cell_phone_confidence', models.CharField(blank=True, max_length=10)),
                ('likelihood_general', models.CharField(blank=True, max_length=20)),
                ('likelihood_primary', models.CharField(blank=True, max_length=20)),
                ('likelihood_combined', models.CharField(blank=True, max_length=20)),
                ('voting_history', models.JSONField(blank=True, default=dict, help_text="Historical voting data, e.g., {'general_2024': True, 'primary_2022': False}")),
                ('household_party', models.CharField(blank=True, max_length=100)),
                ('mailing_household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mailing_family_id', models.CharField(blank=True, max_length=50)),
                ('mailing_household_count', models.PositiveIntegerField(blank=True, null=True)),
                ('mailing_household_party', models.CharField(blank=True, max_length=100)),
                ('import_batch', models.CharField(blank=True, help_text='UUID of the import batch', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(help_text='The election this voter record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='civicpulse.election')),
            ],
            options={
                'verbose_name': 'election voter',
                'verbose_name_plural': 'election voters',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='contactattempt',
            name='election_voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='civicpulse.electionvoter'),
        ),
        migrations.AddField(
            model_name='effortassignment',
            name='election_voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effort_assignments', to='civicpulse.electionvoter'),
        ),
        migrations.AddConstraint(
            model_name='effortassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('effort', 'person'), name='unique_person_assignment'),
        ),
        migrations.AddConstraint(
            model_name='effortassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('election_voter__isnull', False)), fields=('effort', 'election_voter'), name='unique_election_voter_assignment'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importjob',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='civicpulse.election'),
        ),
        migrations.AddField(
            model_name='voteraddress',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='civicpulse.electionvoter'),
        ),
        migrations.AddField(
            model_name='contactattempt',
            name='voter_address_visited',
            field=models.ForeignKey(blank=True, help_text='The address visited for door knock attempts (ElectionVoter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_attempts', to='civicpulse.voteraddress'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['effort', 'election_voter'], name='civicpulse__effort__4e2937_idx'),
        ),
        migrations.AddField(
            model_name='voteremail',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='civicpulse.electionvoter'),
        ),
        migrations.AddField(
            model_name='voterphonenumber',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='civicpulse.electionvoter'),
        ),
        migrations.AddIndex(
            model_name='electionvoter',
            index=models.Index(fields=['election', 'voter_id'], name='civicpulse__electio_283410_idx'),
        ),
        migrations.AddIndex(
            model_name='electionvoter',
            index=models.Index(fields=['last_name', 'first_name'], name='civicpulse__last_na_72fd46_idx'),
        ),
        migrations.AddIndex(
            model_name='electionvoter',
            index=models.Index(fields=['election', 'registered_party'], name='civicpulse__electio_1c0e95_idx'),
        ),
        migrations.AddIndex(
            model_name='electionvoter',
            index=models.Index(fields=['election', 'likelihood_general'], name='civicpulse__electio_e60360_idx'),
        ),
        migrations.AddConstraint(
            model_name='electionvoter',
            constraint=models.UniqueConstraint(fields=('election', 'voter_id'), name='unique_voter_per_election'),
        ),
    ]
