# Generated by Django 6.0 on 2025-12-27 06:09

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0009_election_voter_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geocoded location of this address', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='electionvoter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='GPS location (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='voteraddress',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geocoded location of this address', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='GPS location (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('district_type', models.CharField(choices=[('precinct', 'Voting Precinct'), ('congressional', 'Congressional District'), ('state_house', 'State House District'), ('state_senate', 'State Senate District'), ('county', 'County'), ('city', 'City'), ('school_district', 'School District'), ('other', 'Other')], default='precinct', max_length=20)),
                ('identifier', models.CharField(blank=True, help_text='Official district identifier/code', max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geographic boundary of this district', srid=4326)),
                ('source', models.CharField(blank=True, help_text='Data source (e.g., Census TIGER, state GIS)', max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district_type', 'state', 'name'],
                'indexes': [models.Index(fields=['district_type', 'state'], name='civicpulse__distric_2839ea_idx'), models.Index(fields=['identifier'], name='civicpulse__identif_bf7d26_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeocodingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('total_addresses', models.PositiveIntegerField(default=0)),
                ('processed_addresses', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocoding_jobs', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geocoding_jobs', to='civicpulse.election')),
            ],
            options={
                'verbose_name': 'geocoding job',
                'verbose_name_plural': 'geocoding jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeocodingError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_text', models.CharField(max_length=500)),
                ('model_type', models.CharField(help_text='Model type: address, voter_address, election_voter, voter_record', max_length=50)),
                ('model_id', models.UUIDField()),
                ('error_message', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='civicpulse.geocodingjob')),
            ],
            options={
                'verbose_name': 'geocoding error',
                'verbose_name_plural': 'geocoding errors',
                'ordering': ['-created_at'],
            },
        ),
    ]
