# Generated by Django 6.0 on 2025-12-27 06:09

from django.db import migrations


def populate_locations(apps, schema_editor):
    """
    Convert existing latitude/longitude DecimalFields to Point geometry.
    This runs on both SpatiaLite and PostGIS backends.
    """
    from django.contrib.gis.geos import Point

    VoterRecord = apps.get_model("civicpulse", "VoterRecord")
    ElectionVoter = apps.get_model("civicpulse", "ElectionVoter")

    # Update VoterRecord records with coordinates
    batch_size = 1000
    updated = 0
    records = VoterRecord.objects.filter(
        latitude__isnull=False,
        longitude__isnull=False,
        location__isnull=True,
    )
    for record in records.iterator(chunk_size=batch_size):
        record.location = Point(
            float(record.longitude), float(record.latitude), srid=4326
        )
        record.save(update_fields=["location"])
        updated += 1
        if updated % 1000 == 0:
            print(f"  Updated {updated} VoterRecord locations...")

    if updated > 0:
        print(f"  Total VoterRecord locations updated: {updated}")

    # Update ElectionVoter records with coordinates
    updated = 0
    voters = ElectionVoter.objects.filter(
        latitude__isnull=False,
        longitude__isnull=False,
        location__isnull=True,
    )
    for voter in voters.iterator(chunk_size=batch_size):
        voter.location = Point(
            float(voter.longitude), float(voter.latitude), srid=4326
        )
        voter.save(update_fields=["location"])
        updated += 1
        if updated % 1000 == 0:
            print(f"  Updated {updated} ElectionVoter locations...")

    if updated > 0:
        print(f"  Total ElectionVoter locations updated: {updated}")


def reverse_populate(apps, schema_editor):
    """
    Reverse migration - no action needed since original lat/lon are preserved.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0010_add_spatial_fields"),
    ]

    operations = [
        migrations.RunPython(populate_locations, reverse_populate),
    ]
