# Generated by Django 5.2.9 on 2026-01-02 22:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0011_populate_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Smith for Mayor 2024'", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The candidate this campaign supports (optional for issue-based campaigns)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="civicpulse.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        blank=True,
                        help_text="The election this campaign is associated with (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="civicpulse.election",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="contacteffort",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent campaign this drive belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drives",
                to="civicpulse.campaign",
            ),
        ),
    ]
