# Generated by Django 5.2.9 on 2026-01-02 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0012_add_campaign_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to an existing Person record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidacies",
                to="civicpulse.person",
            ),
        ),
    ]
