# Generated by Django 5.2.9 on 2026-01-02 23:26

from django.conf import settings
from django.db import migrations, models


def add_constraint_if_postgres(apps, schema_editor):
    """Add constraint only on PostgreSQL (not SQLite/SpatiaLite)."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            ALTER TABLE civicpulse_effortassignment
            ADD CONSTRAINT assignment_must_have_target
            CHECK (NOT (person_id IS NULL AND election_voter_id IS NULL))
            """
        )


def remove_constraint_if_postgres(apps, schema_editor):
    """Remove constraint only on PostgreSQL."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            ALTER TABLE civicpulse_effortassignment
            DROP CONSTRAINT IF EXISTS assignment_must_have_target
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0013_change_candidate_person_to_set_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_constraint_if_postgres,
            remove_constraint_if_postgres,
        ),
    ]
