# Generated by Django 5.2.9 on 2026-01-03 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0014_add_assignment_target_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        help_text="Stripe charge ID (ch_xxxxx)", max_length=255
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe PaymentIntent ID (pi_xxxxx)",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe customer ID (cus_xxxxx)",
                        max_length=255,
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveIntegerField(
                        help_text="Amount in cents (e.g., 5000 = $50.00)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="Three-letter ISO currency code",
                        max_length=3,
                    ),
                ),
                (
                    "fee_cents",
                    models.PositiveIntegerField(
                        default=0, help_text="Stripe processing fee in cents"
                    ),
                ),
                (
                    "net_cents",
                    models.PositiveIntegerField(
                        default=0, help_text="Net amount after fees in cents"
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        blank=True,
                        help_text="Donor name from Stripe customer or card",
                        max_length=255,
                    ),
                ),
                (
                    "donor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Donor email from Stripe customer",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partial_refund", "Partially Refunded"),
                        ],
                        default="succeeded",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Charge description from Stripe"
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, help_text="Stripe receipt URL"),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=False, help_text="True if from live mode"
                    ),
                ),
                (
                    "charged_at",
                    models.DateTimeField(
                        help_text="When the charge was created in Stripe"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "donation",
                "verbose_name_plural": "donations",
                "ordering": ["-charged_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationSyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "full_sync",
                    models.BooleanField(
                        default=False,
                        help_text="True for full historical sync, False for incremental",
                    ),
                ),
                ("total_charges", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "error_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of error messages encountered during sync",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "donation sync job",
                "verbose_name_plural": "donation sync jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_user_id",
                    models.CharField(
                        help_text="Stripe account ID (acct_xxxxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_publishable_key",
                    models.CharField(
                        blank=True,
                        help_text="Account's publishable key (if provided)",
                        max_length=255,
                    ),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=False,
                        help_text="True if connected in live mode, False for test mode",
                    ),
                ),
                (
                    "access_token_encrypted",
                    models.TextField(help_text="Fernet-encrypted access token"),
                ),
                (
                    "refresh_token_encrypted",
                    models.TextField(
                        blank=True,
                        help_text="Fernet-encrypted refresh token (if provided)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="OAuth scope granted (e.g., 'read_only')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful donation sync", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe connection",
                "verbose_name_plural": "Stripe connections",
            },
        ),
        migrations.AddField(
            model_name="stripeconnection",
            name="campaign",
            field=models.OneToOneField(
                blank=True,
                help_text="Campaign this Stripe account is connected to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_connection",
                to="civicpulse.campaign",
            ),
        ),
        migrations.AddField(
            model_name="stripeconnection",
            name="candidate",
            field=models.OneToOneField(
                blank=True,
                help_text="Candidate this Stripe account is connected to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_connection",
                to="civicpulse.candidate",
            ),
        ),
        migrations.AddField(
            model_name="donationsyncjob",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_jobs",
                to="civicpulse.stripeconnection",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="civicpulse.stripeconnection",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripeconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("campaign__isnull", True), ("candidate__isnull", False)),
                    models.Q(("campaign__isnull", False), ("candidate__isnull", True)),
                    _connector="OR",
                ),
                name="stripe_connection_single_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["connection", "charged_at"],
                name="civicpulse__connect_b680bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["status"], name="civicpulse__status_a52d2b_idx"),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                fields=("connection", "stripe_charge_id"),
                name="unique_donation_per_connection",
            ),
        ),
    ]
