# Generated by Django 5.2.9 on 2026-01-03 02:00

from django.conf import settings
from django.db import migrations, models


def add_constraint_if_not_exists(apps, schema_editor):
    """Add constraint only if it doesn't already exist (handles migration from 0014)."""
    if schema_editor.connection.vendor == "postgresql":
        # Check if constraint already exists
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1 FROM pg_constraint
                WHERE conname = 'assignment_must_have_target'
                """
            )
            if cursor.fetchone():
                # Constraint already exists (added by migration 0014), skip
                return
        # Add constraint if it doesn't exist
        schema_editor.execute(
            """
            ALTER TABLE civicpulse_effortassignment
            ADD CONSTRAINT assignment_must_have_target
            CHECK (NOT (person_id IS NULL AND election_voter_id IS NULL))
            """
        )


def remove_constraint_if_exists(apps, schema_editor):
    """Remove constraint if it exists."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            ALTER TABLE civicpulse_effortassignment
            DROP CONSTRAINT IF EXISTS assignment_must_have_target
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0015_stripe_connection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState to:
        # - Database: Use RunPython that safely checks if constraint exists
        # - State: Register AddConstraint so Django knows the constraint is managed
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_constraint_if_not_exists,
                    remove_constraint_if_exists,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="effortassignment",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("election_voter__isnull", True),
                            ("person__isnull", True),
                            _negated=True,
                        ),
                        name="assignment_must_have_target",
                    ),
                ),
            ],
        ),
    ]
