# Generated by Django 5.2.9 on 2026-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0016_effortassignment_assignment_must_have_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="districts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Geographic districts this election covers",
                related_name="elections",
                to="civicpulse.district",
            ),
        ),
    ]
