# Generated by Django 5.2.9 on 2026-01-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0016_effortassignment_assignment_must_have_target"),
    ]

    operations = [
        # First remove the constraint that references the candidate field
        migrations.RemoveConstraint(
            model_name="stripeconnection",
            name="stripe_connection_single_owner",
        ),
        # Then remove the candidate field
        migrations.RemoveField(
            model_name="stripeconnection",
            name="candidate",
        ),
    ]
