# Generated by Django 5.2.9 on 2026-01-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0017_add_election_districts"),
        ("civicpulse", "0017_remove_stripeconnection_candidate"),
    ]

    operations = []
