# Generated by Django 5.2.9 on 2026-01-03 18:30

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0017_add_election_districts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Cobb County School Board'",
                        max_length=200,
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("school_board", "School Board"),
                            ("board_of_commissioners", "Board of Commissioners"),
                            ("city_council", "City Council"),
                            ("state_senate", "State Senate"),
                            ("state_house", "State House"),
                            ("us_senate", "U.S. Senate"),
                            ("us_house", "U.S. House of Representatives"),
                            ("county_commission", "County Commission"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="US state abbreviation",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "website",
                    models.URLField(blank=True, help_text="Official website"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["organization_type", "state", "name"],
            },
        ),
        migrations.AddField(
            model_name="office",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The governing body this office belongs to (e.g., School Board, City Council)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offices",
                to="civicpulse.organization",
            ),
        ),
    ]
