# Generated by Django 5.2.9 on 2026-01-03 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0018_merge_20260103_1759"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictImportError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature_index",
                    models.IntegerField(
                        help_text="Index of feature in shapefile (-1 for task-level errors)"
                    ),
                ),
                (
                    "feature_identifier",
                    models.CharField(
                        blank=True,
                        help_text="District identifier from shapefile (e.g., GEOID)",
                        max_length=100,
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        blank=True,
                        help_text="District name from shapefile",
                        max_length=200,
                    ),
                ),
                ("error_message", models.TextField()),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "district import error",
                "verbose_name_plural": "district import errors",
                "ordering": ["feature_index", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DistrictImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        help_text="URL to Census Bureau TIGER/Line zip file (census.gov only)",
                        max_length=500,
                    ),
                ),
                (
                    "district_type",
                    models.CharField(
                        choices=[
                            ("precinct", "Voting Precinct"),
                            ("congressional", "Congressional District"),
                            ("state_house", "State House District"),
                            ("state_senate", "State Senate District"),
                            ("county", "County"),
                            ("city", "City"),
                            ("school_district", "School District"),
                            ("other", "Other"),
                        ],
                        help_text="Type of district to import",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Two-letter state code (e.g., GA, CA) - auto-detected from GEOID if not provided",
                        max_length=2,
                    ),
                ),
                (
                    "identifier_field",
                    models.CharField(
                        default="GEOID",
                        help_text="Shapefile attribute for district identifier",
                        max_length=50,
                    ),
                ),
                (
                    "name_field",
                    models.CharField(
                        default="NAME",
                        help_text="Shapefile attribute for district name",
                        max_length=50,
                    ),
                ),
                (
                    "county_field",
                    models.CharField(
                        blank=True,
                        help_text="Shapefile attribute for county name (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when district boundaries took effect",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Census TIGER/Line",
                        help_text="Data source description",
                        max_length=100,
                    ),
                ),
                (
                    "update_existing",
                    models.BooleanField(
                        default=False,
                        help_text="Update existing districts if they already exist",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_features", models.PositiveIntegerField(default=0)),
                ("processed_features", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                (
                    "downloaded_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Temporary file path for downloaded zip",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "district import job",
                "verbose_name_plural": "district import jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stripeconnection",
            name="candidate",
            field=models.OneToOneField(
                blank=True,
                help_text="Candidate this Stripe account is connected to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_connection",
                to="civicpulse.candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripeconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("campaign__isnull", True), ("candidate__isnull", False)),
                    models.Q(("campaign__isnull", False), ("candidate__isnull", True)),
                    _connector="OR",
                ),
                name="stripe_connection_single_owner",
            ),
        ),
        migrations.AddField(
            model_name="districtimportjob",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="district_import_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="districtimporterror",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="civicpulse.districtimportjob",
            ),
        ),
    ]
