# Generated by Django 5.2.9 on 2026-01-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0017_checkingaccount_transaction"),
        ("civicpulse", "0019_add_district_import_job_and_errors"),
    ]

    operations = []
