# Generated by Django 5.2.9 on 2026-01-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0018_organization"),
        ("civicpulse", "0020_merge_20260103_1827"),
    ]

    operations = []
