# Generated by Django 5.2.5 on 2025-08-18 23:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('organizer', 'Organizer'), ('volunteer', 'Volunteer'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('phone_secondary', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('apartment_number', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone Call'), ('text', 'Text Message'), ('email', 'Email'), ('door', 'Door Knock'), ('mail', 'Postal Mail'), ('social', 'Social Media'), ('event', 'Event'), ('other', 'Other')], max_length=20)),
                ('contact_date', models.DateTimeField()),
                ('result', models.CharField(choices=[('contacted', 'Successfully Contacted'), ('no_answer', 'No Answer'), ('left_message', 'Left Message'), ('wrong_number', 'Wrong Number'), ('refused', 'Refused'), ('callback', 'Callback Requested'), ('not_home', 'Not Home'), ('moved', 'Moved'), ('deceased', 'Deceased'), ('other', 'Other')], max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('strong_support', 'Strong Support'), ('support', 'Support'), ('neutral', 'Neutral'), ('oppose', 'Oppose'), ('strong_oppose', 'Strong Oppose'), ('undecided', 'Undecided')], max_length=20)),
                ('issues_discussed', models.JSONField(blank=True, default=list)),
                ('commitments', models.JSONField(blank=True, default=list)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('event', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_made', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='civicpulse.person')),
            ],
            options={
                'db_table': 'contact_attempts',
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='VoterRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('party_affiliation', models.CharField(choices=[('DEM', 'Democratic'), ('REP', 'Republican'), ('IND', 'Independent'), ('GRN', 'Green'), ('LIB', 'Libertarian'), ('OTH', 'Other'), ('NON', 'No Party Affiliation')], default='NON', max_length=3)),
                ('precinct', models.CharField(blank=True, max_length=50)),
                ('ward', models.CharField(blank=True, max_length=50)),
                ('congressional_district', models.CharField(blank=True, max_length=10)),
                ('state_house_district', models.CharField(blank=True, max_length=10)),
                ('state_senate_district', models.CharField(blank=True, max_length=10)),
                ('polling_location', models.CharField(blank=True, max_length=255)),
                ('voting_history', models.JSONField(blank=True, default=list)),
                ('absentee_voter', models.BooleanField(default=False)),
                ('mail_ballot_requested', models.BooleanField(default=False)),
                ('mail_ballot_sent_date', models.DateField(blank=True, null=True)),
                ('mail_ballot_returned_date', models.DateField(blank=True, null=True)),
                ('last_voted_date', models.DateField(blank=True, null=True)),
                ('voter_score', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_record', to='civicpulse.person')),
            ],
            options={
                'db_table': 'voter_records',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization'], name='users_organiz_29ac71_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='persons_last_na_d74ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='persons_email_768727_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone_primary'], name='persons_phone_p_ff181f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['zip_code'], name='persons_zip_cod_95db50_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='persons_created_6ba3d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['contact_date'], name='contact_att_contact_7e48fc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['contact_type'], name='contact_att_contact_ace37c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['result'], name='contact_att_result_a583c4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['sentiment'], name='contact_att_sentime_b5f53d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['follow_up_required', 'follow_up_date'], name='contact_att_follow__63d508_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['campaign'], name='contact_att_campaig_9f98c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['created_at'], name='contact_att_created_4bf072_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['voter_id'], name='voter_recor_voter_i_12e920_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['registration_status'], name='voter_recor_registr_f6cb55_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['party_affiliation'], name='voter_recor_party_a_c1076e_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['precinct'], name='voter_recor_precinc_bd213a_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['ward'], name='voter_recor_ward_dd5e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['last_voted_date'], name='voter_recor_last_vo_41fff1_idx'),
        ),
    ]
