# Generated by Django 5.2.5 on 2025-08-19 00:00

import civicpulse.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, validators=[civicpulse.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, validators=[civicpulse.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, validators=[civicpulse.models.validate_zip_code]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[civicpulse.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='voter_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[civicpulse.models.validate_voter_id]),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone_secondary'], name='persons_phone_s_e307c5_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['state', 'zip_code'], name='persons_state_94d43a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='persons_date_of_281ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_by'], name='persons_created_dd9ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name', 'date_of_birth'], name='persons_first_n_d78895_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['voter_score'], name='voter_recor_voter_s_8c4fab_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['registration_date'], name='voter_recor_registr_0fb2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['congressional_district'], name='voter_recor_congres_377b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['state_house_district'], name='voter_recor_state_h_5582a4_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['state_senate_district'], name='voter_recor_state_s_2ebc44_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['registration_status', 'party_affiliation'], name='voter_recor_registr_f9a016_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['precinct', 'ward'], name='voter_recor_precinc_2cd4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['voter_score', 'last_voted_date'], name='voter_recor_voter_s_aabee5_idx'),
        ),
    ]
