# Generated by Django 5.2.5 on 2025-08-19 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0002_person_deleted_at_person_deleted_by_person_is_active_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_repr', models.CharField(blank=True, help_text='String representation of user at time of action', max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('SOFT_DELETE', 'Soft Deleted'), ('RESTORE', 'Restored'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('VIEW', 'Viewed'), ('PERMISSION_CHANGE', 'Permission Changed'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('VOTER_DATA', 'Voter Data'), ('AUTH', 'Authentication'), ('SYSTEM', 'System'), ('CONTACT', 'Contact Management'), ('ADMIN', 'Administration'), ('SECURITY', 'Security')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('object_repr', models.CharField(help_text='String representation of the affected object', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Field-by-field changes in format: {field: {'old': val, 'new': val}}")),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Complete old state of object', null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='Complete new state of object', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action (e.g., file names, counts)')),
                ('search_vector', models.TextField(blank=True, help_text='Concatenated searchable text for full-text search')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'permissions': [('export_auditlog', 'Can export audit logs'), ('view_sensitive_auditlog', 'Can view sensitive audit information')],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'), models.Index(fields=['category', '-timestamp'], name='audit_logs_categor_411d16_idx'), models.Index(fields=['severity', '-timestamp'], name='audit_logs_severit_83c56b_idx'), models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx')],
            },
        ),
    ]
