# Generated by Django 5.2.5 on 2025-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0003_add_audit_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
