# Generated by Django 5.2.5 on 2025-08-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0003_passwordhistory'),
        ('civicpulse', '0004_fix_audit_log_fields'),
    ]

    operations = [
    ]
