# Generated by Django 6.0 on 2025-12-24 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0004_effortassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("party_affiliation", models.CharField(blank=True, max_length=50)),
                ("is_incumbent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("withdrawn", "Withdrawn"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("campaign_website", models.URLField(blank=True)),
                ("campaign_slogan", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="civicpulse.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-election__year", "person__last_name"],
            },
        ),
        migrations.AddField(
            model_name="contacteffort",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text="Candidate this effort supports",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_efforts",
                to="civicpulse.candidate",
            ),
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "election_type",
                    models.CharField(
                        choices=[
                            ("general", "General Election"),
                            ("primary", "Primary Election"),
                            ("special", "Special Election"),
                            ("runoff", "Runoff Election"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(help_text="Election year (e.g., 2024)"),
                ),
                ("qualifying_start", models.DateField(blank=True, null=True)),
                ("qualifying_end", models.DateField(blank=True, null=True)),
                ("registration_deadline", models.DateField(blank=True, null=True)),
                ("absentee_request_deadline", models.DateField(blank=True, null=True)),
                ("early_voting_start", models.DateField(blank=True, null=True)),
                ("early_voting_end", models.DateField(blank=True, null=True)),
                ("election_day", models.DateField(blank=True, null=True)),
                ("certification_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("certified", "Certified"),
                        ],
                        default="upcoming",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_election",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent election (e.g., the General election this Primary feeds into)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_elections",
                        to="civicpulse.election",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-election_day"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="civicpulse.election",
            ),
        ),
        migrations.AddField(
            model_name="contacteffort",
            name="election",
            field=models.ForeignKey(
                blank=True,
                help_text="Election this effort is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_efforts",
                to="civicpulse.election",
            ),
        ),
        migrations.CreateModel(
            name="ElectionDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_type",
                    models.CharField(
                        choices=[
                            ("candidate_forum", "Candidate Forum"),
                            ("debate", "Debate"),
                            ("filing_deadline", "Filing Deadline"),
                            ("campaign_event", "Campaign Event"),
                            ("fundraising_deadline", "Fundraising Deadline"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_dates",
                        to="civicpulse.election",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Mayor', 'City Council Seat 3'", max_length=200
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "State"),
                            ("county", "County"),
                            ("city", "City"),
                            ("school_district", "School District"),
                            ("other", "Other"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="US state abbreviation", max_length=2
                    ),
                ),
                (
                    "term_length_years",
                    models.PositiveIntegerField(
                        blank=True, help_text="Term length in years", null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level", "state", "city", "name"],
                "indexes": [
                    models.Index(fields=["level"], name="civicpulse__level_820e0d_idx"),
                    models.Index(
                        fields=["state", "city"], name="civicpulse__state_61dd0a_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="election",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elections",
                to="civicpulse.office",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["status"], name="civicpulse__status_6158a5_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["party_affiliation"], name="civicpulse__party_a_08c78f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("person", "election")},
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(fields=["year"], name="civicpulse__year_648ea5_idx"),
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(fields=["status"], name="civicpulse__status_97de38_idx"),
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(
                fields=["election_day"], name="civicpulse__electio_ce4714_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(
                fields=["office", "year"], name="civicpulse__office__c83935_idx"
            ),
        ),
    ]
