# Generated by Django 6.0 on 2025-12-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicpulse", "0005_candidate_contacteffort_candidate_election_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("no_answer", "No Answer"),
                    ("busy", "Busy Signal"),
                    ("left_voicemail", "Left Voicemail"),
                    ("wrong_number", "Wrong Number"),
                    ("spoke_with", "Spoke With Person"),
                    ("will_vote", "Will Vote for Candidate"),
                    ("refused", "Refused/Do Not Contact"),
                    ("callback_requested", "Callback Requested"),
                ],
                max_length=20,
            ),
        ),
    ]
