# Generated by Django 5.2.5 on 2025-11-07 23:58

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    """
    Add case-insensitive index on email field for optimized duplicate detection.

    The Person model's get_potential_duplicates() method uses email__iexact
    for case-insensitive email matching. This migration adds a functional index
    on LOWER(email) to optimize these queries.

    This index works in both SQLite (development) and PostgreSQL (production).
    """

    dependencies = [
        ('civicpulse', '0007_test_migration_safety'),
    ]

    operations = [
        # Add case-insensitive email index for duplicate detection
        # This optimizes the email__iexact queries in get_potential_duplicates()
        migrations.AddIndex(
            model_name='person',
            index=models.Index(
                Lower('email'),
                name='idx_person_email_lower',
            ),
        ),
    ]
