# Generated by Olivia Johnson on 2025-11-11

from datetime import date, timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_campaign_charfield_to_foreignkey(apps, schema_editor):
    """
    Migrate existing campaign CharField values to Campaign ForeignKey.

    This function:
    1. Extracts all unique non-empty campaign names from
       ContactAttempt.campaign CharField
    2. Creates Campaign records for each unique name
    3. Links ContactAttempt records to the corresponding Campaign
       via campaign_new
    """
    ContactAttempt = apps.get_model("civicpulse", "ContactAttempt")
    Campaign = apps.get_model("civicpulse", "Campaign")
    User = apps.get_model("auth", "User")

    # Get all unique non-empty campaign names
    unique_campaign_names = (
        ContactAttempt.objects.exclude(campaign="")
        .values_list("campaign", flat=True)
        .distinct()
    )

    if not unique_campaign_names:
        # No data to migrate
        return

    # Get first admin user or None
    first_admin = User.objects.filter(is_superuser=True).first()

    # Create Campaign records for each unique name
    campaign_mapping = {}
    for campaign_name in unique_campaign_names:
        campaign, created = Campaign.objects.get_or_create(
            name=campaign_name.strip(),
            defaults={
                "description": (f"Migrated from ContactAttempt data on {date.today()}"),
                "candidate_name": "Unknown",
                # 1 year placeholder
                "election_date": date.today() + timedelta(days=365),
                "status": "active",
                "created_by": first_admin,
            },
        )
        campaign_mapping[campaign_name] = campaign

    # Update ContactAttempt records to link to the new Campaign ForeignKey
    for contact_attempt in ContactAttempt.objects.exclude(campaign=""):
        campaign_name = contact_attempt.campaign
        if campaign_name in campaign_mapping:
            contact_attempt.campaign_new = campaign_mapping[campaign_name]
            contact_attempt.save(update_fields=["campaign_new"])


def reverse_migrate_campaign_foreignkey_to_charfield(apps, schema_editor):
    """
    Reverse migration: Copy Campaign names back to CharField.

    This allows rolling back the migration if needed.
    """
    ContactAttempt = apps.get_model("civicpulse", "ContactAttempt")

    # Copy campaign names from ForeignKey back to CharField
    for contact_attempt in ContactAttempt.objects.filter(campaign_new__isnull=False):
        contact_attempt.campaign = contact_attempt.campaign_new.name
        contact_attempt.save(update_fields=["campaign"])


class Migration(migrations.Migration):
    dependencies = [
        ("civicpulse", "0009_campaign_remove_person_idx_person_email_lower_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove the index on the old campaign CharField to avoid SQLite issues
        migrations.RemoveIndex(
            model_name="contactattempt",
            name="contact_att_campaig_9f98c1_idx",
        ),
        # Step 2: Add new ForeignKey field with temporary name
        migrations.AddField(
            model_name="contactattempt",
            name="campaign_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_attempts_new",
                to="civicpulse.campaign",
            ),
        ),
        # Step 3: Run data migration to populate campaign_new from campaign CharField
        migrations.RunPython(
            migrate_campaign_charfield_to_foreignkey,
            reverse_migrate_campaign_foreignkey_to_charfield,
        ),
        # Step 4: Remove the old campaign CharField
        migrations.RemoveField(
            model_name="contactattempt",
            name="campaign",
        ),
        # Step 5: Rename campaign_new to campaign
        # Note: Django automatically creates an index for ForeignKey fields
        migrations.RenameField(
            model_name="contactattempt",
            old_name="campaign_new",
            new_name="campaign",
        ),
    ]
