# Generated by Django 5.2.8 on 2025-11-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0010_migrate_campaign_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='idx_person_email_lower',
        ),
        migrations.AlterField(
            model_name='contactattempt',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_attempts', to='civicpulse.campaign'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['campaign'], name='contact_att_campaig_396684_idx'),
        ),
    ]
