# Generated by Django 5.2.8 on 2025-11-11 23:36

import civicpulse.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0011_remove_person_idx_person_email_lower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('district_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('district_type', models.CharField(choices=[('federal_senate', 'Federal Senate'), ('federal_house', 'Federal House'), ('state_senate', 'State Senate'), ('state_house', 'State House'), ('county', 'County'), ('school_board', 'School Board'), ('municipality', 'Municipality'), ('other', 'Other')], max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('boundary_description', models.TextField(blank=True)),
                ('counties_covered', models.JSONField(blank=True, default=list)),
                ('zip_codes_covered', models.JSONField(blank=True, default=list)),
                ('election_authority', models.CharField(blank=True, max_length=255)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Districts',
                'db_table': 'districts',
                'ordering': ['state', 'district_type', 'name'],
                'indexes': [models.Index(fields=['district_code'], name='districts_distric_6063ed_idx'), models.Index(fields=['district_type'], name='districts_distric_35b5e8_idx'), models.Index(fields=['state'], name='districts_state_a6d5bb_idx'), models.Index(fields=['state', 'district_type'], name='districts_state_4e74e4_idx'), models.Index(fields=['is_active'], name='districts_is_acti_a43f13_idx')],
            },
        ),
        migrations.CreateModel(
            name='Officeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('party_affiliation', models.CharField(blank=True, max_length=50)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, validators=[civicpulse.models.validate_phone_number])),
                ('office_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('office_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officeholders', to='civicpulse.district')),
            ],
            options={
                'db_table': 'officeholders',
                'ordering': ['-is_current', '-term_start'],
                'indexes': [models.Index(fields=['is_current'], name='officeholde_is_curr_623211_idx'), models.Index(fields=['district'], name='officeholde_distric_c4af77_idx'), models.Index(fields=['last_name', 'first_name'], name='officeholde_last_na_7099d0_idx'), models.Index(fields=['term_start'], name='officeholde_term_st_0a0162_idx'), models.Index(fields=['term_end'], name='officeholde_term_en_f550e2_idx'), models.Index(fields=['district', 'is_current'], name='officeholde_distric_d7ec53_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonDistrict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_method', models.CharField(choices=[('manual', 'Manual Assignment'), ('voter_record', 'Voter Record'), ('geocoding', 'Geocoding'), ('zip_match', 'ZIP Code Match'), ('import', 'Data Import')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('current_officeholder_name', models.CharField(blank=True, max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_people', to='civicpulse.district')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_districts', to='civicpulse.person')),
            ],
            options={
                'db_table': 'person_districts',
                'indexes': [models.Index(fields=['person', 'district'], name='person_dist_person__359b90_idx'), models.Index(fields=['district', 'assignment_method'], name='person_dist_distric_a31cb6_idx'), models.Index(fields=['assigned_at'], name='person_dist_assigne_a2786d_idx'), models.Index(fields=['confidence'], name='person_dist_confide_b01799_idx')],
                'unique_together': {('person', 'district')},
            },
        ),
    ]
