# Generated by Django 5.2.8 on 2025-11-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0012_district_officeholder_persondistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scope',
            field=models.CharField(choices=[('district', 'Single District'), ('multi_district', 'Multiple Districts'), ('statewide', 'Statewide'), ('national', 'National')], default='district', help_text='Geographical scope of the campaign', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_districts',
            field=models.ManyToManyField(blank=True, help_text='Districts this campaign targets for contact outreach', related_name='campaigns', to='civicpulse.district'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scope'], name='civicpulse__scope_c34148_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scope', 'status'], name='civicpulse__scope_3a1848_idx'),
        ),
    ]
